-- ─────────────────────────────────────────────────────────────────────────────
-- project_email_eventos — bitácora de lo que Resend hace con cada correo.
--
-- POR QUÉ EXISTE: la API de Resend (GET /emails) NO permite filtrar por
-- destinatario, solo paginar de 100 en 100. Para responder «¿le llegó el correo
-- a este alumno?» habría que recorrer miles de registros en cada consulta. En su
-- lugar, el webhook de Resend nos empuja cada evento y lo guardamos aquí, donde
-- sí podemos buscar por email al instante.
--
-- OJO: solo hay datos desde que se activa el webhook. No existe histórico previo.
--
-- Namespace project_* = app Acelerador (base compartida del ecosistema).
-- Migración ADITIVA e IDEMPOTENTE: se puede correr varias veces sin daño.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.project_email_eventos (
  id           bigint generated by default as identity primary key,
  email        text        not null,
  resend_id    text,                    -- id del email en Resend (agrupa eventos)
  tipo         text        not null,    -- email.sent | email.delivered | email.bounced | ...
  asunto       text,
  ocurrido_en  timestamptz not null default now(),
  payload      jsonb,                   -- evento completo, para depurar
  creado_en    timestamptz not null default now()
);

-- Búsqueda por correo: siempre consultamos en minúsculas.
create index if not exists project_email_eventos_email_idx
  on public.project_email_eventos (lower(email));

-- Para pedir «el último evento de este correo».
create index if not exists project_email_eventos_ocurrido_idx
  on public.project_email_eventos (ocurrido_en desc);

-- Resend reintenta los webhooks: el mismo evento puede llegar dos veces.
-- Este índice hace que el segundo intento choque y lo podamos ignorar.
create unique index if not exists project_email_eventos_unico_idx
  on public.project_email_eventos (resend_id, tipo)
  where resend_id is not null;

-- RLS activada y SIN políticas: nadie con anon key puede leer ni escribir.
-- El único acceso es por backend con service_role, que se salta RLS.
alter table public.project_email_eventos enable row level security;
